---
- name: Install necessary packages
  apt:
    update_cache: yes
    cache_valid_time: 86400
    name: "{{ item }}"
    state: latest
  with_items:
    - lftp
  when: "{{ raspicam_offsite_image_copy_enable_ftp }} == True"

- name: add remote server's ssh key to known_hosts
  shell: ssh-keyscan {{ item }} >> ~/.ssh/known_hosts
  with_items:
    - "{{ groups['webservers'] }}"

- name: copy crontab template to the place
  template:
    dest: /etc/cron.d/{{ item }}
    src: crontab.tmpl
    mode: 0600
  with_items:
    - "{{ groups['webservers'] | regex_replace('\\.','')}}"
